printf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");

printf("Hello");
printf("Hello");
PRINTF("Hello");

prinstf("Hello");

prinstf("Hello");

prinstf("Hello");

prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
printsfs("Hsell");
prinstf("Hello");
prinstf("Hello");
printf("Hsesllodafnjka("Hello"
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
printprintfss("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
prinstf("Hello");
